server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Check for literal file, then directory, then fallback to React's index.html
        try_files $uri $uri/ /index.html;
    }
}
